dist: xenial
addons:
    chrome: stable
language: python
jobs:
  include:
    - stage: linting
      python: "3.6"
      before_install:
        - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        - source $HOME/.poetry/env
      install:
        - pip install pre-commit
        - pre-commit install-hooks
        - poetry install
      script:
        - pre-commit run --all-files
    - stage: test
      python: "3.6"
      before_install:
        - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
        - source $HOME/.poetry/env
      install:
        - pip install poetry
        - poetry install
      script:
          - pytest -v
          - black --check --verbose .

