dist: trusty
addons:
    chrome: stable

language: python

python:
    - 3.6
before_install:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
    - poetry install
    - pytest -v
